// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: immat.proto

package org.sdia.immatriculation.GRPC_Service.stubs;

public final class Immat {
  private Immat() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface proprietaireOrBuilder extends
      // @@protoc_insertion_point(interface_extends:proprietaire)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double idp = 1;</code>
     * @return The idp.
     */
    double getIdp();

    /**
     * <code>string nom = 2;</code>
     * @return The nom.
     */
    java.lang.String getNom();
    /**
     * <code>string nom = 2;</code>
     * @return The bytes for nom.
     */
    com.google.protobuf.ByteString
        getNomBytes();

    /**
     * <code>string dateNaissance = 3;</code>
     * @return The dateNaissance.
     */
    java.lang.String getDateNaissance();
    /**
     * <code>string dateNaissance = 3;</code>
     * @return The bytes for dateNaissance.
     */
    com.google.protobuf.ByteString
        getDateNaissanceBytes();
  }
  /**
   * Protobuf type {@code proprietaire}
   */
  public  static final class proprietaire extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:proprietaire)
      proprietaireOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use proprietaire.newBuilder() to construct.
    private proprietaire(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private proprietaire() {
      nom_ = "";
      dateNaissance_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new proprietaire();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private proprietaire(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              idp_ = input.readDouble();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              nom_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              dateNaissance_ = s;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sdia.immatriculation.GRPC_Service.stubs.Immat.internal_static_proprietaire_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sdia.immatriculation.GRPC_Service.stubs.Immat.internal_static_proprietaire_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.class, org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.Builder.class);
    }

    public static final int IDP_FIELD_NUMBER = 1;
    private double idp_;
    /**
     * <code>double idp = 1;</code>
     * @return The idp.
     */
    public double getIdp() {
      return idp_;
    }

    public static final int NOM_FIELD_NUMBER = 2;
    private volatile java.lang.Object nom_;
    /**
     * <code>string nom = 2;</code>
     * @return The nom.
     */
    public java.lang.String getNom() {
      java.lang.Object ref = nom_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        nom_ = s;
        return s;
      }
    }
    /**
     * <code>string nom = 2;</code>
     * @return The bytes for nom.
     */
    public com.google.protobuf.ByteString
        getNomBytes() {
      java.lang.Object ref = nom_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        nom_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int DATENAISSANCE_FIELD_NUMBER = 3;
    private volatile java.lang.Object dateNaissance_;
    /**
     * <code>string dateNaissance = 3;</code>
     * @return The dateNaissance.
     */
    public java.lang.String getDateNaissance() {
      java.lang.Object ref = dateNaissance_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        dateNaissance_ = s;
        return s;
      }
    }
    /**
     * <code>string dateNaissance = 3;</code>
     * @return The bytes for dateNaissance.
     */
    public com.google.protobuf.ByteString
        getDateNaissanceBytes() {
      java.lang.Object ref = dateNaissance_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        dateNaissance_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (idp_ != 0D) {
        output.writeDouble(1, idp_);
      }
      if (!getNomBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, nom_);
      }
      if (!getDateNaissanceBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, dateNaissance_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (idp_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, idp_);
      }
      if (!getNomBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, nom_);
      }
      if (!getDateNaissanceBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, dateNaissance_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire)) {
        return super.equals(obj);
      }
      org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire other = (org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire) obj;

      if (java.lang.Double.doubleToLongBits(getIdp())
          != java.lang.Double.doubleToLongBits(
              other.getIdp())) return false;
      if (!getNom()
          .equals(other.getNom())) return false;
      if (!getDateNaissance()
          .equals(other.getDateNaissance())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDP_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getIdp()));
      hash = (37 * hash) + NOM_FIELD_NUMBER;
      hash = (53 * hash) + getNom().hashCode();
      hash = (37 * hash) + DATENAISSANCE_FIELD_NUMBER;
      hash = (53 * hash) + getDateNaissance().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code proprietaire}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:proprietaire)
        org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaireOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sdia.immatriculation.GRPC_Service.stubs.Immat.internal_static_proprietaire_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sdia.immatriculation.GRPC_Service.stubs.Immat.internal_static_proprietaire_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.class, org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.Builder.class);
      }

      // Construct using org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idp_ = 0D;

        nom_ = "";

        dateNaissance_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sdia.immatriculation.GRPC_Service.stubs.Immat.internal_static_proprietaire_descriptor;
      }

      @java.lang.Override
      public org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire getDefaultInstanceForType() {
        return org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.getDefaultInstance();
      }

      @java.lang.Override
      public org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire build() {
        org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire buildPartial() {
        org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire result = new org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire(this);
        result.idp_ = idp_;
        result.nom_ = nom_;
        result.dateNaissance_ = dateNaissance_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire) {
          return mergeFrom((org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire other) {
        if (other == org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.getDefaultInstance()) return this;
        if (other.getIdp() != 0D) {
          setIdp(other.getIdp());
        }
        if (!other.getNom().isEmpty()) {
          nom_ = other.nom_;
          onChanged();
        }
        if (!other.getDateNaissance().isEmpty()) {
          dateNaissance_ = other.dateNaissance_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double idp_ ;
      /**
       * <code>double idp = 1;</code>
       * @return The idp.
       */
      public double getIdp() {
        return idp_;
      }
      /**
       * <code>double idp = 1;</code>
       * @param value The idp to set.
       * @return This builder for chaining.
       */
      public Builder setIdp(double value) {
        
        idp_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double idp = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdp() {
        
        idp_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object nom_ = "";
      /**
       * <code>string nom = 2;</code>
       * @return The nom.
       */
      public java.lang.String getNom() {
        java.lang.Object ref = nom_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          nom_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string nom = 2;</code>
       * @return The bytes for nom.
       */
      public com.google.protobuf.ByteString
          getNomBytes() {
        java.lang.Object ref = nom_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          nom_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string nom = 2;</code>
       * @param value The nom to set.
       * @return This builder for chaining.
       */
      public Builder setNom(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        nom_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string nom = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNom() {
        
        nom_ = getDefaultInstance().getNom();
        onChanged();
        return this;
      }
      /**
       * <code>string nom = 2;</code>
       * @param value The bytes for nom to set.
       * @return This builder for chaining.
       */
      public Builder setNomBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        nom_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object dateNaissance_ = "";
      /**
       * <code>string dateNaissance = 3;</code>
       * @return The dateNaissance.
       */
      public java.lang.String getDateNaissance() {
        java.lang.Object ref = dateNaissance_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          dateNaissance_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string dateNaissance = 3;</code>
       * @return The bytes for dateNaissance.
       */
      public com.google.protobuf.ByteString
          getDateNaissanceBytes() {
        java.lang.Object ref = dateNaissance_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          dateNaissance_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string dateNaissance = 3;</code>
       * @param value The dateNaissance to set.
       * @return This builder for chaining.
       */
      public Builder setDateNaissance(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        dateNaissance_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string dateNaissance = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearDateNaissance() {
        
        dateNaissance_ = getDefaultInstance().getDateNaissance();
        onChanged();
        return this;
      }
      /**
       * <code>string dateNaissance = 3;</code>
       * @param value The bytes for dateNaissance to set.
       * @return This builder for chaining.
       */
      public Builder setDateNaissanceBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        dateNaissance_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:proprietaire)
    }

    // @@protoc_insertion_point(class_scope:proprietaire)
    private static final org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire();
    }

    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<proprietaire>
        PARSER = new com.google.protobuf.AbstractParser<proprietaire>() {
      @java.lang.Override
      public proprietaire parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new proprietaire(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<proprietaire> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<proprietaire> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface vehiculeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:vehicule)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double idv = 1;</code>
     * @return The idv.
     */
    double getIdv();

    /**
     * <code>string numMatricule = 2;</code>
     * @return The numMatricule.
     */
    java.lang.String getNumMatricule();
    /**
     * <code>string numMatricule = 2;</code>
     * @return The bytes for numMatricule.
     */
    com.google.protobuf.ByteString
        getNumMatriculeBytes();

    /**
     * <code>string marque = 3;</code>
     * @return The marque.
     */
    java.lang.String getMarque();
    /**
     * <code>string marque = 3;</code>
     * @return The bytes for marque.
     */
    com.google.protobuf.ByteString
        getMarqueBytes();

    /**
     * <code>int32 puissanceFiscal = 4;</code>
     * @return The puissanceFiscal.
     */
    int getPuissanceFiscal();

    /**
     * <code>string modele = 5;</code>
     * @return The modele.
     */
    java.lang.String getModele();
    /**
     * <code>string modele = 5;</code>
     * @return The bytes for modele.
     */
    com.google.protobuf.ByteString
        getModeleBytes();

    /**
     * <code>.proprietaire idProprietaire = 6;</code>
     * @return Whether the idProprietaire field is set.
     */
    boolean hasIdProprietaire();
    /**
     * <code>.proprietaire idProprietaire = 6;</code>
     * @return The idProprietaire.
     */
    org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire getIdProprietaire();
    /**
     * <code>.proprietaire idProprietaire = 6;</code>
     */
    org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaireOrBuilder getIdProprietaireOrBuilder();
  }
  /**
   * Protobuf type {@code vehicule}
   */
  public  static final class vehicule extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:vehicule)
      vehiculeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use vehicule.newBuilder() to construct.
    private vehicule(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private vehicule() {
      numMatricule_ = "";
      marque_ = "";
      modele_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new vehicule();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private vehicule(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              idv_ = input.readDouble();
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              numMatricule_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              marque_ = s;
              break;
            }
            case 32: {

              puissanceFiscal_ = input.readInt32();
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              modele_ = s;
              break;
            }
            case 50: {
              org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.Builder subBuilder = null;
              if (idProprietaire_ != null) {
                subBuilder = idProprietaire_.toBuilder();
              }
              idProprietaire_ = input.readMessage(org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(idProprietaire_);
                idProprietaire_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sdia.immatriculation.GRPC_Service.stubs.Immat.internal_static_vehicule_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sdia.immatriculation.GRPC_Service.stubs.Immat.internal_static_vehicule_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule.class, org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule.Builder.class);
    }

    public static final int IDV_FIELD_NUMBER = 1;
    private double idv_;
    /**
     * <code>double idv = 1;</code>
     * @return The idv.
     */
    public double getIdv() {
      return idv_;
    }

    public static final int NUMMATRICULE_FIELD_NUMBER = 2;
    private volatile java.lang.Object numMatricule_;
    /**
     * <code>string numMatricule = 2;</code>
     * @return The numMatricule.
     */
    public java.lang.String getNumMatricule() {
      java.lang.Object ref = numMatricule_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        numMatricule_ = s;
        return s;
      }
    }
    /**
     * <code>string numMatricule = 2;</code>
     * @return The bytes for numMatricule.
     */
    public com.google.protobuf.ByteString
        getNumMatriculeBytes() {
      java.lang.Object ref = numMatricule_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        numMatricule_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int MARQUE_FIELD_NUMBER = 3;
    private volatile java.lang.Object marque_;
    /**
     * <code>string marque = 3;</code>
     * @return The marque.
     */
    public java.lang.String getMarque() {
      java.lang.Object ref = marque_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        marque_ = s;
        return s;
      }
    }
    /**
     * <code>string marque = 3;</code>
     * @return The bytes for marque.
     */
    public com.google.protobuf.ByteString
        getMarqueBytes() {
      java.lang.Object ref = marque_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        marque_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PUISSANCEFISCAL_FIELD_NUMBER = 4;
    private int puissanceFiscal_;
    /**
     * <code>int32 puissanceFiscal = 4;</code>
     * @return The puissanceFiscal.
     */
    public int getPuissanceFiscal() {
      return puissanceFiscal_;
    }

    public static final int MODELE_FIELD_NUMBER = 5;
    private volatile java.lang.Object modele_;
    /**
     * <code>string modele = 5;</code>
     * @return The modele.
     */
    public java.lang.String getModele() {
      java.lang.Object ref = modele_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        modele_ = s;
        return s;
      }
    }
    /**
     * <code>string modele = 5;</code>
     * @return The bytes for modele.
     */
    public com.google.protobuf.ByteString
        getModeleBytes() {
      java.lang.Object ref = modele_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modele_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int IDPROPRIETAIRE_FIELD_NUMBER = 6;
    private org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire idProprietaire_;
    /**
     * <code>.proprietaire idProprietaire = 6;</code>
     * @return Whether the idProprietaire field is set.
     */
    public boolean hasIdProprietaire() {
      return idProprietaire_ != null;
    }
    /**
     * <code>.proprietaire idProprietaire = 6;</code>
     * @return The idProprietaire.
     */
    public org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire getIdProprietaire() {
      return idProprietaire_ == null ? org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.getDefaultInstance() : idProprietaire_;
    }
    /**
     * <code>.proprietaire idProprietaire = 6;</code>
     */
    public org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaireOrBuilder getIdProprietaireOrBuilder() {
      return getIdProprietaire();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (idv_ != 0D) {
        output.writeDouble(1, idv_);
      }
      if (!getNumMatriculeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, numMatricule_);
      }
      if (!getMarqueBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, marque_);
      }
      if (puissanceFiscal_ != 0) {
        output.writeInt32(4, puissanceFiscal_);
      }
      if (!getModeleBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, modele_);
      }
      if (idProprietaire_ != null) {
        output.writeMessage(6, getIdProprietaire());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (idv_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, idv_);
      }
      if (!getNumMatriculeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, numMatricule_);
      }
      if (!getMarqueBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, marque_);
      }
      if (puissanceFiscal_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, puissanceFiscal_);
      }
      if (!getModeleBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, modele_);
      }
      if (idProprietaire_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getIdProprietaire());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule)) {
        return super.equals(obj);
      }
      org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule other = (org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule) obj;

      if (java.lang.Double.doubleToLongBits(getIdv())
          != java.lang.Double.doubleToLongBits(
              other.getIdv())) return false;
      if (!getNumMatricule()
          .equals(other.getNumMatricule())) return false;
      if (!getMarque()
          .equals(other.getMarque())) return false;
      if (getPuissanceFiscal()
          != other.getPuissanceFiscal()) return false;
      if (!getModele()
          .equals(other.getModele())) return false;
      if (hasIdProprietaire() != other.hasIdProprietaire()) return false;
      if (hasIdProprietaire()) {
        if (!getIdProprietaire()
            .equals(other.getIdProprietaire())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + IDV_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getIdv()));
      hash = (37 * hash) + NUMMATRICULE_FIELD_NUMBER;
      hash = (53 * hash) + getNumMatricule().hashCode();
      hash = (37 * hash) + MARQUE_FIELD_NUMBER;
      hash = (53 * hash) + getMarque().hashCode();
      hash = (37 * hash) + PUISSANCEFISCAL_FIELD_NUMBER;
      hash = (53 * hash) + getPuissanceFiscal();
      hash = (37 * hash) + MODELE_FIELD_NUMBER;
      hash = (53 * hash) + getModele().hashCode();
      if (hasIdProprietaire()) {
        hash = (37 * hash) + IDPROPRIETAIRE_FIELD_NUMBER;
        hash = (53 * hash) + getIdProprietaire().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code vehicule}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:vehicule)
        org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehiculeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sdia.immatriculation.GRPC_Service.stubs.Immat.internal_static_vehicule_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sdia.immatriculation.GRPC_Service.stubs.Immat.internal_static_vehicule_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule.class, org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule.Builder.class);
      }

      // Construct using org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        idv_ = 0D;

        numMatricule_ = "";

        marque_ = "";

        puissanceFiscal_ = 0;

        modele_ = "";

        if (idProprietaireBuilder_ == null) {
          idProprietaire_ = null;
        } else {
          idProprietaire_ = null;
          idProprietaireBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sdia.immatriculation.GRPC_Service.stubs.Immat.internal_static_vehicule_descriptor;
      }

      @java.lang.Override
      public org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule getDefaultInstanceForType() {
        return org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule.getDefaultInstance();
      }

      @java.lang.Override
      public org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule build() {
        org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule buildPartial() {
        org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule result = new org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule(this);
        result.idv_ = idv_;
        result.numMatricule_ = numMatricule_;
        result.marque_ = marque_;
        result.puissanceFiscal_ = puissanceFiscal_;
        result.modele_ = modele_;
        if (idProprietaireBuilder_ == null) {
          result.idProprietaire_ = idProprietaire_;
        } else {
          result.idProprietaire_ = idProprietaireBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule) {
          return mergeFrom((org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule other) {
        if (other == org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule.getDefaultInstance()) return this;
        if (other.getIdv() != 0D) {
          setIdv(other.getIdv());
        }
        if (!other.getNumMatricule().isEmpty()) {
          numMatricule_ = other.numMatricule_;
          onChanged();
        }
        if (!other.getMarque().isEmpty()) {
          marque_ = other.marque_;
          onChanged();
        }
        if (other.getPuissanceFiscal() != 0) {
          setPuissanceFiscal(other.getPuissanceFiscal());
        }
        if (!other.getModele().isEmpty()) {
          modele_ = other.modele_;
          onChanged();
        }
        if (other.hasIdProprietaire()) {
          mergeIdProprietaire(other.getIdProprietaire());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double idv_ ;
      /**
       * <code>double idv = 1;</code>
       * @return The idv.
       */
      public double getIdv() {
        return idv_;
      }
      /**
       * <code>double idv = 1;</code>
       * @param value The idv to set.
       * @return This builder for chaining.
       */
      public Builder setIdv(double value) {
        
        idv_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double idv = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdv() {
        
        idv_ = 0D;
        onChanged();
        return this;
      }

      private java.lang.Object numMatricule_ = "";
      /**
       * <code>string numMatricule = 2;</code>
       * @return The numMatricule.
       */
      public java.lang.String getNumMatricule() {
        java.lang.Object ref = numMatricule_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          numMatricule_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string numMatricule = 2;</code>
       * @return The bytes for numMatricule.
       */
      public com.google.protobuf.ByteString
          getNumMatriculeBytes() {
        java.lang.Object ref = numMatricule_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          numMatricule_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string numMatricule = 2;</code>
       * @param value The numMatricule to set.
       * @return This builder for chaining.
       */
      public Builder setNumMatricule(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        numMatricule_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string numMatricule = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearNumMatricule() {
        
        numMatricule_ = getDefaultInstance().getNumMatricule();
        onChanged();
        return this;
      }
      /**
       * <code>string numMatricule = 2;</code>
       * @param value The bytes for numMatricule to set.
       * @return This builder for chaining.
       */
      public Builder setNumMatriculeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        numMatricule_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object marque_ = "";
      /**
       * <code>string marque = 3;</code>
       * @return The marque.
       */
      public java.lang.String getMarque() {
        java.lang.Object ref = marque_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          marque_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string marque = 3;</code>
       * @return The bytes for marque.
       */
      public com.google.protobuf.ByteString
          getMarqueBytes() {
        java.lang.Object ref = marque_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          marque_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string marque = 3;</code>
       * @param value The marque to set.
       * @return This builder for chaining.
       */
      public Builder setMarque(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        marque_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string marque = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMarque() {
        
        marque_ = getDefaultInstance().getMarque();
        onChanged();
        return this;
      }
      /**
       * <code>string marque = 3;</code>
       * @param value The bytes for marque to set.
       * @return This builder for chaining.
       */
      public Builder setMarqueBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        marque_ = value;
        onChanged();
        return this;
      }

      private int puissanceFiscal_ ;
      /**
       * <code>int32 puissanceFiscal = 4;</code>
       * @return The puissanceFiscal.
       */
      public int getPuissanceFiscal() {
        return puissanceFiscal_;
      }
      /**
       * <code>int32 puissanceFiscal = 4;</code>
       * @param value The puissanceFiscal to set.
       * @return This builder for chaining.
       */
      public Builder setPuissanceFiscal(int value) {
        
        puissanceFiscal_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 puissanceFiscal = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPuissanceFiscal() {
        
        puissanceFiscal_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object modele_ = "";
      /**
       * <code>string modele = 5;</code>
       * @return The modele.
       */
      public java.lang.String getModele() {
        java.lang.Object ref = modele_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          modele_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string modele = 5;</code>
       * @return The bytes for modele.
       */
      public com.google.protobuf.ByteString
          getModeleBytes() {
        java.lang.Object ref = modele_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          modele_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string modele = 5;</code>
       * @param value The modele to set.
       * @return This builder for chaining.
       */
      public Builder setModele(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        modele_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string modele = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearModele() {
        
        modele_ = getDefaultInstance().getModele();
        onChanged();
        return this;
      }
      /**
       * <code>string modele = 5;</code>
       * @param value The bytes for modele to set.
       * @return This builder for chaining.
       */
      public Builder setModeleBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        modele_ = value;
        onChanged();
        return this;
      }

      private org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire idProprietaire_;
      private com.google.protobuf.SingleFieldBuilderV3<
          org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire, org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.Builder, org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaireOrBuilder> idProprietaireBuilder_;
      /**
       * <code>.proprietaire idProprietaire = 6;</code>
       * @return Whether the idProprietaire field is set.
       */
      public boolean hasIdProprietaire() {
        return idProprietaireBuilder_ != null || idProprietaire_ != null;
      }
      /**
       * <code>.proprietaire idProprietaire = 6;</code>
       * @return The idProprietaire.
       */
      public org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire getIdProprietaire() {
        if (idProprietaireBuilder_ == null) {
          return idProprietaire_ == null ? org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.getDefaultInstance() : idProprietaire_;
        } else {
          return idProprietaireBuilder_.getMessage();
        }
      }
      /**
       * <code>.proprietaire idProprietaire = 6;</code>
       */
      public Builder setIdProprietaire(org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire value) {
        if (idProprietaireBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          idProprietaire_ = value;
          onChanged();
        } else {
          idProprietaireBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.proprietaire idProprietaire = 6;</code>
       */
      public Builder setIdProprietaire(
          org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.Builder builderForValue) {
        if (idProprietaireBuilder_ == null) {
          idProprietaire_ = builderForValue.build();
          onChanged();
        } else {
          idProprietaireBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.proprietaire idProprietaire = 6;</code>
       */
      public Builder mergeIdProprietaire(org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire value) {
        if (idProprietaireBuilder_ == null) {
          if (idProprietaire_ != null) {
            idProprietaire_ =
              org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.newBuilder(idProprietaire_).mergeFrom(value).buildPartial();
          } else {
            idProprietaire_ = value;
          }
          onChanged();
        } else {
          idProprietaireBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.proprietaire idProprietaire = 6;</code>
       */
      public Builder clearIdProprietaire() {
        if (idProprietaireBuilder_ == null) {
          idProprietaire_ = null;
          onChanged();
        } else {
          idProprietaire_ = null;
          idProprietaireBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.proprietaire idProprietaire = 6;</code>
       */
      public org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.Builder getIdProprietaireBuilder() {
        
        onChanged();
        return getIdProprietaireFieldBuilder().getBuilder();
      }
      /**
       * <code>.proprietaire idProprietaire = 6;</code>
       */
      public org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaireOrBuilder getIdProprietaireOrBuilder() {
        if (idProprietaireBuilder_ != null) {
          return idProprietaireBuilder_.getMessageOrBuilder();
        } else {
          return idProprietaire_ == null ?
              org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.getDefaultInstance() : idProprietaire_;
        }
      }
      /**
       * <code>.proprietaire idProprietaire = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire, org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.Builder, org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaireOrBuilder> 
          getIdProprietaireFieldBuilder() {
        if (idProprietaireBuilder_ == null) {
          idProprietaireBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire, org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaire.Builder, org.sdia.immatriculation.GRPC_Service.stubs.Immat.proprietaireOrBuilder>(
                  getIdProprietaire(),
                  getParentForChildren(),
                  isClean());
          idProprietaire_ = null;
        }
        return idProprietaireBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:vehicule)
    }

    // @@protoc_insertion_point(class_scope:vehicule)
    private static final org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule();
    }

    public static org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<vehicule>
        PARSER = new com.google.protobuf.AbstractParser<vehicule>() {
      @java.lang.Override
      public vehicule parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new vehicule(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<vehicule> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<vehicule> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.sdia.immatriculation.GRPC_Service.stubs.Immat.vehicule getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_proprietaire_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_proprietaire_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_vehicule_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_vehicule_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013immat.proto\"?\n\014proprietaire\022\013\n\003idp\030\001 \001" +
      "(\001\022\013\n\003nom\030\002 \001(\t\022\025\n\rdateNaissance\030\003 \001(\t\"\215" +
      "\001\n\010vehicule\022\013\n\003idv\030\001 \001(\001\022\024\n\014numMatricule" +
      "\030\002 \001(\t\022\016\n\006marque\030\003 \001(\t\022\027\n\017puissanceFisca" +
      "l\030\004 \001(\005\022\016\n\006modele\030\005 \001(\t\022%\n\016idProprietair" +
      "e\030\006 \001(\0132\r.proprietaire2m\n\026Immatriculatio" +
      "nService\022,\n\014affichagePro\022\r.proprietaire\032" +
      "\r.proprietaire\022%\n\raffichageVehi\022\t.vehicu" +
      "le\032\t.vehiculeB-\n+org.sdia.immatriculatio" +
      "n.GRPC_Service.stubsb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_proprietaire_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_proprietaire_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_proprietaire_descriptor,
        new java.lang.String[] { "Idp", "Nom", "DateNaissance", });
    internal_static_vehicule_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_vehicule_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_vehicule_descriptor,
        new java.lang.String[] { "Idv", "NumMatricule", "Marque", "PuissanceFiscal", "Modele", "IdProprietaire", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
