spring:
  cloud:
     gateway:
       routes:
           - id: r1
             uri: http://localhost:8084/
             predicates:
               - Path= /vehicules/**

           - id: r2
             uri: http://localhost:8084/
             predicates:
               - Path= /proprietaires/**

           - id: r3
             uri: http://localhost:8081/
             predicates:
               - Path= /radars/**

           - id: r4
             uri: http://localhost:8082/
             predicates:
               - Path= /infractions/**

     discovery:
       enabled: true
server:
   port: 8888