// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Detect.proto

package org.sdia.Radar.DetectGrpcService.Stubs;

public final class Detect {
  private Detect() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface DetectVitesseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:DetectVitesse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string vehiculeMatriculation = 1;</code>
     * @return The vehiculeMatriculation.
     */
    java.lang.String getVehiculeMatriculation();
    /**
     * <code>string vehiculeMatriculation = 1;</code>
     * @return The bytes for vehiculeMatriculation.
     */
    com.google.protobuf.ByteString
        getVehiculeMatriculationBytes();

    /**
     * <code>double vehiculeVitesse = 2;</code>
     * @return The vehiculeVitesse.
     */
    double getVehiculeVitesse();

    /**
     * <code>double IdRadar = 3;</code>
     * @return The idRadar.
     */
    double getIdRadar();
  }
  /**
   * Protobuf type {@code DetectVitesse}
   */
  public  static final class DetectVitesse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:DetectVitesse)
      DetectVitesseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use DetectVitesse.newBuilder() to construct.
    private DetectVitesse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private DetectVitesse() {
      vehiculeMatriculation_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new DetectVitesse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private DetectVitesse(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              vehiculeMatriculation_ = s;
              break;
            }
            case 17: {

              vehiculeVitesse_ = input.readDouble();
              break;
            }
            case 25: {

              idRadar_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sdia.Radar.DetectGrpcService.Stubs.Detect.internal_static_DetectVitesse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sdia.Radar.DetectGrpcService.Stubs.Detect.internal_static_DetectVitesse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse.class, org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse.Builder.class);
    }

    public static final int VEHICULEMATRICULATION_FIELD_NUMBER = 1;
    private volatile java.lang.Object vehiculeMatriculation_;
    /**
     * <code>string vehiculeMatriculation = 1;</code>
     * @return The vehiculeMatriculation.
     */
    public java.lang.String getVehiculeMatriculation() {
      java.lang.Object ref = vehiculeMatriculation_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        vehiculeMatriculation_ = s;
        return s;
      }
    }
    /**
     * <code>string vehiculeMatriculation = 1;</code>
     * @return The bytes for vehiculeMatriculation.
     */
    public com.google.protobuf.ByteString
        getVehiculeMatriculationBytes() {
      java.lang.Object ref = vehiculeMatriculation_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        vehiculeMatriculation_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int VEHICULEVITESSE_FIELD_NUMBER = 2;
    private double vehiculeVitesse_;
    /**
     * <code>double vehiculeVitesse = 2;</code>
     * @return The vehiculeVitesse.
     */
    public double getVehiculeVitesse() {
      return vehiculeVitesse_;
    }

    public static final int IDRADAR_FIELD_NUMBER = 3;
    private double idRadar_;
    /**
     * <code>double IdRadar = 3;</code>
     * @return The idRadar.
     */
    public double getIdRadar() {
      return idRadar_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getVehiculeMatriculationBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, vehiculeMatriculation_);
      }
      if (vehiculeVitesse_ != 0D) {
        output.writeDouble(2, vehiculeVitesse_);
      }
      if (idRadar_ != 0D) {
        output.writeDouble(3, idRadar_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getVehiculeMatriculationBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, vehiculeMatriculation_);
      }
      if (vehiculeVitesse_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, vehiculeVitesse_);
      }
      if (idRadar_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, idRadar_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse)) {
        return super.equals(obj);
      }
      org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse other = (org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse) obj;

      if (!getVehiculeMatriculation()
          .equals(other.getVehiculeMatriculation())) return false;
      if (java.lang.Double.doubleToLongBits(getVehiculeVitesse())
          != java.lang.Double.doubleToLongBits(
              other.getVehiculeVitesse())) return false;
      if (java.lang.Double.doubleToLongBits(getIdRadar())
          != java.lang.Double.doubleToLongBits(
              other.getIdRadar())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + VEHICULEMATRICULATION_FIELD_NUMBER;
      hash = (53 * hash) + getVehiculeMatriculation().hashCode();
      hash = (37 * hash) + VEHICULEVITESSE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getVehiculeVitesse()));
      hash = (37 * hash) + IDRADAR_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getIdRadar()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code DetectVitesse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:DetectVitesse)
        org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sdia.Radar.DetectGrpcService.Stubs.Detect.internal_static_DetectVitesse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sdia.Radar.DetectGrpcService.Stubs.Detect.internal_static_DetectVitesse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse.class, org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse.Builder.class);
      }

      // Construct using org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        vehiculeMatriculation_ = "";

        vehiculeVitesse_ = 0D;

        idRadar_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sdia.Radar.DetectGrpcService.Stubs.Detect.internal_static_DetectVitesse_descriptor;
      }

      @java.lang.Override
      public org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse getDefaultInstanceForType() {
        return org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse.getDefaultInstance();
      }

      @java.lang.Override
      public org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse build() {
        org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse buildPartial() {
        org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse result = new org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse(this);
        result.vehiculeMatriculation_ = vehiculeMatriculation_;
        result.vehiculeVitesse_ = vehiculeVitesse_;
        result.idRadar_ = idRadar_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse) {
          return mergeFrom((org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse other) {
        if (other == org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse.getDefaultInstance()) return this;
        if (!other.getVehiculeMatriculation().isEmpty()) {
          vehiculeMatriculation_ = other.vehiculeMatriculation_;
          onChanged();
        }
        if (other.getVehiculeVitesse() != 0D) {
          setVehiculeVitesse(other.getVehiculeVitesse());
        }
        if (other.getIdRadar() != 0D) {
          setIdRadar(other.getIdRadar());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object vehiculeMatriculation_ = "";
      /**
       * <code>string vehiculeMatriculation = 1;</code>
       * @return The vehiculeMatriculation.
       */
      public java.lang.String getVehiculeMatriculation() {
        java.lang.Object ref = vehiculeMatriculation_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          vehiculeMatriculation_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string vehiculeMatriculation = 1;</code>
       * @return The bytes for vehiculeMatriculation.
       */
      public com.google.protobuf.ByteString
          getVehiculeMatriculationBytes() {
        java.lang.Object ref = vehiculeMatriculation_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          vehiculeMatriculation_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string vehiculeMatriculation = 1;</code>
       * @param value The vehiculeMatriculation to set.
       * @return This builder for chaining.
       */
      public Builder setVehiculeMatriculation(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        vehiculeMatriculation_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string vehiculeMatriculation = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehiculeMatriculation() {
        
        vehiculeMatriculation_ = getDefaultInstance().getVehiculeMatriculation();
        onChanged();
        return this;
      }
      /**
       * <code>string vehiculeMatriculation = 1;</code>
       * @param value The bytes for vehiculeMatriculation to set.
       * @return This builder for chaining.
       */
      public Builder setVehiculeMatriculationBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        vehiculeMatriculation_ = value;
        onChanged();
        return this;
      }

      private double vehiculeVitesse_ ;
      /**
       * <code>double vehiculeVitesse = 2;</code>
       * @return The vehiculeVitesse.
       */
      public double getVehiculeVitesse() {
        return vehiculeVitesse_;
      }
      /**
       * <code>double vehiculeVitesse = 2;</code>
       * @param value The vehiculeVitesse to set.
       * @return This builder for chaining.
       */
      public Builder setVehiculeVitesse(double value) {
        
        vehiculeVitesse_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double vehiculeVitesse = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearVehiculeVitesse() {
        
        vehiculeVitesse_ = 0D;
        onChanged();
        return this;
      }

      private double idRadar_ ;
      /**
       * <code>double IdRadar = 3;</code>
       * @return The idRadar.
       */
      public double getIdRadar() {
        return idRadar_;
      }
      /**
       * <code>double IdRadar = 3;</code>
       * @param value The idRadar to set.
       * @return This builder for chaining.
       */
      public Builder setIdRadar(double value) {
        
        idRadar_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double IdRadar = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearIdRadar() {
        
        idRadar_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:DetectVitesse)
    }

    // @@protoc_insertion_point(class_scope:DetectVitesse)
    private static final org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse();
    }

    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<DetectVitesse>
        PARSER = new com.google.protobuf.AbstractParser<DetectVitesse>() {
      @java.lang.Override
      public DetectVitesse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new DetectVitesse(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<DetectVitesse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<DetectVitesse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.sdia.Radar.DetectGrpcService.Stubs.Detect.DetectVitesse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Response)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 response = 1;</code>
     * @return The response.
     */
    int getResponse();
  }
  /**
   * Protobuf type {@code Response}
   */
  public  static final class Response extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Response)
      ResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Response.newBuilder() to construct.
    private Response(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Response() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Response();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Response(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              response_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.sdia.Radar.DetectGrpcService.Stubs.Detect.internal_static_Response_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.sdia.Radar.DetectGrpcService.Stubs.Detect.internal_static_Response_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response.class, org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response.Builder.class);
    }

    public static final int RESPONSE_FIELD_NUMBER = 1;
    private int response_;
    /**
     * <code>int32 response = 1;</code>
     * @return The response.
     */
    public int getResponse() {
      return response_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (response_ != 0) {
        output.writeInt32(1, response_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (response_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, response_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response)) {
        return super.equals(obj);
      }
      org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response other = (org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response) obj;

      if (getResponse()
          != other.getResponse()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + RESPONSE_FIELD_NUMBER;
      hash = (53 * hash) + getResponse();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Response}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Response)
        org.sdia.Radar.DetectGrpcService.Stubs.Detect.ResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.sdia.Radar.DetectGrpcService.Stubs.Detect.internal_static_Response_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.sdia.Radar.DetectGrpcService.Stubs.Detect.internal_static_Response_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response.class, org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response.Builder.class);
      }

      // Construct using org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        response_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.sdia.Radar.DetectGrpcService.Stubs.Detect.internal_static_Response_descriptor;
      }

      @java.lang.Override
      public org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response getDefaultInstanceForType() {
        return org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response.getDefaultInstance();
      }

      @java.lang.Override
      public org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response build() {
        org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response buildPartial() {
        org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response result = new org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response(this);
        result.response_ = response_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response) {
          return mergeFrom((org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response other) {
        if (other == org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response.getDefaultInstance()) return this;
        if (other.getResponse() != 0) {
          setResponse(other.getResponse());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int response_ ;
      /**
       * <code>int32 response = 1;</code>
       * @return The response.
       */
      public int getResponse() {
        return response_;
      }
      /**
       * <code>int32 response = 1;</code>
       * @param value The response to set.
       * @return This builder for chaining.
       */
      public Builder setResponse(int value) {
        
        response_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 response = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponse() {
        
        response_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Response)
    }

    // @@protoc_insertion_point(class_scope:Response)
    private static final org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response();
    }

    public static org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Response>
        PARSER = new com.google.protobuf.AbstractParser<Response>() {
      @java.lang.Override
      public Response parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Response(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Response> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Response> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public org.sdia.Radar.DetectGrpcService.Stubs.Detect.Response getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_DetectVitesse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_DetectVitesse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Response_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Response_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Detect.proto\"X\n\rDetectVitesse\022\035\n\025vehic" +
      "uleMatriculation\030\001 \001(\t\022\027\n\017vehiculeVitess" +
      "e\030\002 \001(\001\022\017\n\007IdRadar\030\003 \001(\001\"\034\n\010Response\022\020\n\010" +
      "response\030\001 \001(\00529\n\rDetectService\022(\n\007envoy" +
      "er\022\016.DetectVitesse\032\t.Response(\0010\001B(\n&org" +
      ".sdia.Radar.DetectGrpcService.Stubsb\006pro" +
      "to3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_DetectVitesse_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_DetectVitesse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_DetectVitesse_descriptor,
        new java.lang.String[] { "VehiculeMatriculation", "VehiculeVitesse", "IdRadar", });
    internal_static_Response_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Response_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Response_descriptor,
        new java.lang.String[] { "Response", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
